# All SpaceVim option below [option] section
[options]
	# Spacevim 使用dein 进行plugin管理  
    #################################################################
    # options for basic
    #################################################################
	# Change the default indentation of SpaceVim. Default is 2.
    default_indent = 4
	# Use the appropriate number of spaces to insert a <Tab>
    expand_tab = false
	# Enable/Disable relativenumber in current windows, by default it is enabled.
    relativenumber = false
	# Change the max number of columns for SpaceVim. Default is 120.
    max_column = 512
	# Enable/Disable cursorline. Default is true, cursorline will be highlighted in normal mode
    enable_cursorline = true
	# Enable/Disable cursorcolumn. Default is 0, cursorcolumn will be highlighted in normal mode.
	enable_cursorcolumn = false

    #################################################################
    # options for file manager
    #################################################################
    filemanager = "defx"
	filetree_direction = "left"

	# 让file tree 显示文件图标，需要 terminal 安装 nerd font
	enable_vimfiler_filetypeicon = true
	# 让 filetree 显示 git 的状态，会变得很卡，所以关掉
	# enable_vimfiler_gitstatus = true
	# 设置文件树默认关闭
	enable_vimfiler_welcome = false

    #################################################################
    # VIM 兼容模式
    #################################################################
    # VIM 兼容模式
    # vimcompatible = true
    windows_leader = ''
    # enable_language_specific_leader = false

    #################################################################
    # options for 主题 和 颜色
    #################################################################
    # 设置 SpaceVim 主题及背景，默认的主题是 gruvbox，如果你需要使用更
    # 多的主题，你可以载入 colorscheme 模块
    # colorscheme = "gruvbox"
    # colorscheme = "molokai"
    
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    
    # colorscheme = "NeoSolarized"
    # colorscheme_bg = "light"
    # 背景可以取值 "dark" 和 "light"

    # 启用/禁用终端真色，在目前大多数终端下都是支持真色的，当然也有
    # 一小部分终端不支持真色，如果你的 SpaceVim 颜色看上去比较怪异
    # 可以禁用终端真色，将下面的值设为 false
    enable_guicolors = true


    #################################################################
    # options for module statusline
    #################################################################
    # 设置状态栏上分割符号形状，如果字体安装失败，可以将值设为 "nil" 以禁用分割符号，
    # 分割符包括以下几种 "arrow", "curve", "slant", "fire", "nil"，默认为箭头 "arrow"
    # 设置活动窗口状态栏上的分割符号形状
    statusline_separator = "arrow"
    # 设置非活动窗口状态栏上的分割符号形状
    statusline_iseparator = "arrow"

    # 设置顶部标签列表序号类型，有以下五种类型，分别是 0 - 4
    # 0: 1 ➛ ➊
    # 1: 1 ➛ ➀
    # 2: 1 ➛ ⓵
    # 3: 1 ➛ ¹
    # 4: 1 ➛ 1
    buffer_index_type = 2
	# types:
	# 0: 1 ➛ ➊
	# 1: 1 ➛ ➀
	# 2: 1 ➛ ⓵
	# 3: 1 ➛ 1
	windows_index_type = 2

    # 是否在状态栏上显示当前模式，默认情况下，不显示 Normal/Insert 等
    enable_statusline_mode = false

    # 状态栏左端部分的构成
    statusline_left_sections = ['winnr', 'filename', 'version control info', 'search status']
    # 状态栏右端部分的构成
    statusline_right_sections = ['input method', 'major mode', 'minor mode lighters', 'fileformat', 'cursorpos', 'percentage']
    # 列表可以由以下一项或多项组成

    # 'winnr' 当前窗口编号
    # 'syntax checking'
    # 'filename' 文件名
    # 'fileformat' 文件格式
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' 光标位置
    # 'percentage' 百分比
    # 'date' 日期
    # 'time' 时间
    # 'whitespace' 打开或者保存文件时，如果第 n 行的行尾有空格则显示 trailing[n]，并不能实时显示出行尾有空格的行号。
    # 'battery status' 电池状态
    # 'input method' 输入法
    # 'search status' 搜索状态

    #################################################################
    # options for module chinese
    #################################################################
    vim_help_language = "cn"

    #################################################################
	# 启动自定义的vim配置
    #################################################################
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"

    #################################################################
    # autocomplete
    #################################################################
	#% cmake -H. -BDebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=YES
	#% ln -s Debug/compile_commands.json .
    autocomplete_method = "coc"
	# autocomplete 括号
	autocomplete_parens = true
    #################################################################
    # google suggestions
    #################################################################
	enable_googlesuggest = true

#################################################################
#	默认的layer
#################################################################
[[layers]]
    name = "checkers"
	enable = false
[[layers]]
    name = "chinese"
[[layers]]
    name = "core#banner"
[[layers]]
    name = "core#tabline"
	# 支持 Leader + idx 快捷键快速跳转
[[layers]]
    name = "core#statusline"
	# 如果打开大文件 运行会卡  就把这个layer关掉
	enable = false
[[layers]]
    name = "core"
	# defx: file tree
	# comment
[[layers]]
    name = "edit"
	# multi cursor
	# eazy motion	
[[layers]]
    name = "format"
[[layers]]
    name = "ui"

#################################################################
#	添加的layer
#################################################################
# 版本控制
[[layers]]
	name = "VersionControl"
	enable-gtm-status = true
[[layers]]
	name = "git"
	git-plugin = "fugitive"
[[layers]]
	name = "fzf"
# [[layers]]
# 	name = "lang#markdown"
[[layers]]
	name = 'shell'
	default_position = 'bottom'
	default_height = 30
[[layers]]
  name = "lang#groovy"
# Enable autocomplete layer
[[layers]]
	name = 'autocomplete'
	auto_completion_return_key_behavior = "complete"
	auto_completion_tab_key_behavior = "smart"
	auto_completion_delay = 50
	auto_completion_complete_with_key_sequence = "nil"
	auto_completion_complete_with_key_sequence_delay = 0.1
	enable = true

# The lsp layer has to be enabled too. SpaceVim converts the configuration in the lsp layer and then passes it to coc.
# You can put your language servers here.
[[layers]] 
	name = 'lsp'
  	# filetypes = [
  	#   'c',
  	#   'cpp'
  	# ]
  	# [layers.override_cmd]
  	#   c = ['ccls', '--log-file=/tmp/ccls.log']
  	#   cpp = ['ccls', '--log-file=/tmp/ccls.log']
[[layers]]
	name = "lang#c"
  	clang_executable = "/usr/bin/clang"
  	[layer.clang_std]
		c = "c11"
  	  	cpp = "c++1z"
  	  	objc = "c11"
  	  	objcpp = "c++1z"
#################################################################
#	custom plugin
#################################################################
# 基于lsp的高亮插件
[[custom_plugins]]
    name = 'jackguo380/vim-lsp-cxx-highlight'
	merged = false

# vista.vim 的依赖
[[custom_plugins]]
	name = 'junegunn/fzf.vim'
	merged = false

# 更加美观的 tagbar
[[custom_plugins]]
    name = 'liuchengxu/vista.vim'
	merged = false

# 比 nerdcommentary 更好用的注释工具
[[custom_plugins]]
    name = 'tpope/vim-commentary'
	merged = false

# 更加方便的调节窗口的大小
[[custom_plugins]]
    name = 'simeji/winresizer'
	merged = false

# copilot
[[custom_plugins]]
    name = 'github/copilot.vim'
	merged = false
